name: E2E Frontend Tests

on: push

jobs:
  e2e-test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install Dependencies
      run: |
        cd frontend
        npm ci  # Install dependencies for the frontend

    - name: Start Frontend
      run: |
        cd frontend
        npm run dev &  # Start frontend in the background

    - name: Wait for App to Start
      run: sleep 10 

    - name: Run Puppeteer Test (TypeScript)
      run: |
        cd frontend
        npm run test

    - name: Stop React App
      run: |
        kill $(lsof -t -i:5173) || true  # Stop the app running on port 5173 (Vite default)
