name: E2E Backend Tests - User Service

on: push

jobs:
  backend-test-user-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install Dependencies
      run: |
        cd backend/microservices/user-service/functions
        npm ci

    - name: Install ts-node and TypeScript
      run: |
        cd backend/microservices/user-service/functions
        npm install -D ts-node typescript

    - name: Run Tests
      run: |
        cd backend/microservices/user-service/functions
        npm run test:coverage